name: Build & Push Docker Images

on:
  push:
    branches: 
      - dev_docker

env:
  DOCKERHUB_USERNAME: infiloop

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push Docker image
        id: build_core
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: share/docker
          file: ./Dockerfile
          push: false
          target: core
          tags: infispiel/darshan_util_dxtthread:latest

      - name: Build and push development Docker image
        id: build_dev
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: share/docker
          file: ./Dockerfile
          push: false
          tags: infispiel/darshan_util_dxtthread_dev:latest
